name: demo1

on : push

jobs: 
    demo1:
        runs-on: ubuntu-latest
        name: just print
        steps: 
            - name: echo command
              run: | 
                echo "aloha praveen"
                ls -la
                echo "vanakam di mapla"