name: demo1

on : push

jobs: 
    demo1:
        runs-on: ubuntu-latest
        name: cowsay demo
        steps: 
            - name: repo checkout
              uses: actions/checkout@v4

            - name: echo command
              run: | 
                ls -la